name: "bundlephobia-pr-review"
description: "Check for new packages and their sizes"
branding:
  icon: 'package'  
  color: 'black'
inputs:
  repo-token: # id of input
    description: "Github token secret"
    required: true
  strict: # id of input
    description: "Should block pr if threshold not pass?"
  threshold: # id of input
    description: "Maximum size in bytes of a package gziped"
    default: 600
runs:
  using: "node12"
  main: "dist/index.js"
